version: '3'
services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: Y
    ports:
      - 1433:1433
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "yourStrong(!)Password", "-Q", "select 1"]
      interval: 10s
      retries: 10
  octopus:
    image: octopusdeploy/octopusdeploy
    environment:
      ACCEPT_EULA: Y
      DB_CONNECTION_STRING: Server=db,1433;Database=OctopusDeploy;User=sa;Password=yourStrong(!)Password
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: testtest123
      ADMIN_API_KEY: API-TESTTEST123TRESDTSDD
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db