name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
#          needed for FirstCommitHashTaskTest
          fetch-depth: 0
      - name: Cache
        uses: gradle/gradle-build-action@v2.4.2
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Download and Install Octo CLI
        run: |
          wget https://github.com/OctopusDeploy/OctopusCLI/releases/download/v9.1.7/OctopusTools.9.1.7.linux-x64.tar.gz
          mkdir -p $HOME/.local/bin
          tar -xzf OctopusTools.9.1.7.linux-x64.tar.gz -C $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Build
        run: ./gradlew build
      - name: Validate
        run: ./gradlew check validatePlugins --continue
      - name: Integration Test
        run: |
          octo --version
          java -version
          ./gradlew integrationTest --no-daemon
