name: Pre Merge Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
#          needed for FirstCommitHashTaskTest
          fetch-depth: 0
      - name: Cache
        uses: gradle/gradle-build-action@v2.4.2
      - name: Build
        run: ./gradlew build
      - name: Validate
        run: ./gradlew check validatePlugins --continue
