name: Publish to Gradle Plugin Portal

on:
  push:
    tags:
      - '*'

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          #          needed for FirstCommitHashTaskTest
          fetch-depth: 0
      - name: Cache
        uses: gradle/gradle-build-action@v2
      - name: Build
        run: ./gradlew build
      - name: Validate
        run: ./gradlew validatePlugins --continue
      - name: Publish
        run: ./gradlew publishPlugins
